# Generated by Django 6.0.3 on 2026-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.BigIntegerField(blank=True, null=True)),
                ('run_ts', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('segment', models.CharField(blank=True, max_length=20)),
                ('marketplace', models.CharField(blank=True, max_length=50)),
                ('marketplace_label', models.CharField(blank=True, max_length=50)),
                ('po', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('warehouse', models.CharField(blank=True, max_length=20)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=10)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('output_file', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order header',
                'db_table': 'order_headers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.BigIntegerField(blank=True, null=True)),
                ('run_ts', models.DateTimeField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=50)),
                ('po', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('item_no', models.CharField(blank=True, max_length=50)),
                ('ean', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=10)),
                ('gst_code', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vendor_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('our_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vendor_landing', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('our_landing', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vendor_cp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('our_cp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diff', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('exception_label', models.CharField(blank=True, max_length=50)),
                ('output_file', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order line',
                'db_table': 'order_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_ts', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplaces', models.IntegerField(blank=True, null=True)),
                ('total_pos', models.IntegerField(blank=True, null=True)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('total_qty', models.IntegerField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('consolidated_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tracker_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Run',
                'db_table': 'runs',
                'managed': False,
            },
        ),
    ]
