"""
Django settings for renee_cosmetics project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Online PO engine (Phase 0) ──────────────────────────────────────────
# Option A: import the existing `online_po_processor` package as a LIBRARY
# (no fork, no copy). The Tkinter app keeps using the same source untouched.
# online_po_management/ is a sibling of this settings package at the repo root.
ENGINE_ROOT = BASE_DIR / 'online_po_management'
if ENGINE_ROOT.is_dir() and str(ENGINE_ROOT) not in sys.path:
    sys.path.insert(0, str(ENGINE_ROOT))

# ── Config from a project-root .env (optional, host-friendly) ────────────
# Lets DJANGO_* vars + ONLINE_PO_DB_CONFIG live in one .env file (handy on
# PythonAnywhere / any host). No-op when python-dotenv or .env is absent — the
# app still reads real OS environment variables exactly as before. See
# .env.example + PYTHONANYWHERE.md. Never commit the real .env (it's gitignored).
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:  # noqa: BLE001 — dotenv optional; OS env still works
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Override via env (DJANGO_SECRET_KEY) when hosting; falls back to dev key.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    "django-insecure-p&*^wtu2w@s_w_a)ei_#h5-f4#qknjc1hqb&t7-=(4!zs3m4$(")

# SECURITY WARNING: don't run with debug turned on in production!
# Hosting sets DJANGO_DEBUG=0 (see serve.bat / HOSTING.md). Default = dev (on).
DEBUG = os.environ.get('DJANGO_DEBUG', '1') != '0'

# Fail fast: never serve production (DEBUG off) with the committed insecure dev
# key — a host that forgets DJANGO_SECRET_KEY must NOT boot silently exposed.
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError(
        "DJANGO_SECRET_KEY is still the insecure dev fallback but DEBUG is off. "
        "Set a real DJANGO_SECRET_KEY before hosting (see .env.example / "
        "PYTHONANYWHERE.md).")

# LAN hosting: allow the office subnet by default; override with DJANGO_ALLOWED_HOSTS
# (comma-separated). '*' is fine for a trusted internal network.
ALLOWED_HOSTS = [h.strip() for h in
                 os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

# CSRF: HTTPS hosts (e.g. PythonAnywhere) require the site origin WITH scheme for
# POST forms to be accepted. Comma-separated, e.g.
# "https://USERNAME.pythonanywhere.com". Empty on LAN/dev (plain HTTP).
CSRF_TRUSTED_ORIGINS = [o.strip() for o in
                        os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
                        if o.strip()]
if _render_host:
    _render_origin = f'https://{_render_host}'
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

# ── Production HTTPS hardening (opt-in) ──────────────────────────────────
# Set DJANGO_SECURE_SSL=1 on an HTTPS host (e.g. PythonAnywhere). LAN/dev runs on
# plain HTTP, so this stays OFF by default (else it would break local access).
# PythonAnywhere terminates SSL at its proxy and forwards X-Forwarded-Proto, so
# we trust that header for the redirect + secure-cookie flags.
if os.environ.get('DJANGO_SECURE_SSL', '') == '1':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS is opt-in via seconds (0 = off). Be careful on a shared domain like
    # *.pythonanywhere.com — read Django's HSTS docs before enabling.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '0'))
    if SECURE_HSTS_SECONDS:
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    'offline',
    'online_b2b',
    'returns',
    'online_b2c',
    'inventory',
    'other',
    'grn',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves collected static files directly from the WSGI app
    # (waitress) — no nginx needed for LAN hosting. Must sit right after Security.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # RBAC write-guard — denies POST/PUT/PATCH/DELETE from non-Editors by default
    # (read-only exports/searches/previews allowlisted). Must sit AFTER
    # AuthenticationMiddleware so request.user exists. Additive: Editors + all
    # GET traffic pass untouched. See core/access.py.
    "core.access.WriteGuardMiddleware",
    # Dev · Health perf capture — innermost, times the view + DB. Additive;
    # appends to logs/perf.jsonl, never alters the response or the business DB.
    "core.observability.PerfMiddleware",
]

ROOT_URLCONF = "renee_cosmetics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'core', 'templates')],
        # NB: APP_DIRS must be omitted when 'loaders' is set (mutually exclusive).
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "online_b2b.context_processors.build_info",
                "core.access.roles",
            ],
            # Explicit UNCACHED loaders → template/HTML/chart edits go live on the
            # prod server (DEBUG=0) with just a browser refresh, no restart. The
            # per-request read cost is microseconds (fine for a LAN pilot).
            # (Python/view/settings changes still need a waitress restart.)
            "loaders": [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "renee_cosmetics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ── Order DB (MySQL renee_orders) for admin CRUD ────────────────────────
# Same credentials the engine uses (db_config.json, kept OUT of the repo).
# The read-only dashboards use raw pymysql; this Django ORM 'orders' connection
# powers the admin CRUD on managed=False models. A router (OrdersRouter) keeps
# ALL migrations OFF this connection — Django never creates/alters/drops the
# engine-owned tables, so the schema + data are never reset. Admin edits/deletes
# only the specific rows an admin acts on.
def _load_orders_db():
    # ONE config source for the whole app (engine + web + this ORM connection):
    # history_db.load_db_config() = db_config.json file OR host env vars (DB_*).
    # mysql_ssl() adds TLS for TiDB. So the SAME code runs locally (file) and on
    # the server (env vars), against local MySQL or TiDB.
    try:
        from online_po_processor.auto.history_db import load_db_config, mysql_ssl
        cfg = load_db_config()
    except Exception:  # noqa: BLE001 — engine not importable ⇒ sqlite only
        return None
    if not cfg or str(cfg.get('backend', '')).lower() != 'mysql':
        return None
    opts = {'charset': 'utf8mb4'}
    ssl = mysql_ssl(cfg)
    if ssl.get('ssl') is not None:
        opts['ssl'] = ssl['ssl']
    return {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': cfg.get('database', 'renee_orders'),
        'USER': cfg.get('user', 'root'),
        'PASSWORD': cfg.get('password', ''),
        'HOST': cfg.get('host', '127.0.0.1'),
        'PORT': str(cfg.get('port', 3306)),
        'OPTIONS': opts,
        'TIME_ZONE': 'UTC',
        # PERSISTENT connections: without this Django opens a FRESH TLS connection to
        # TiDB on EVERY request (~700-800 ms handshake to a remote DB) for auth +
        # sessions — the uniform per-page slowdown. Keep the connection warm across
        # requests; CONN_HEALTH_CHECKS pings a possibly-stale one once per request
        # (cheap) and reconnects, so a TiDB idle-timeout drop can't error a request.
        'CONN_MAX_AGE': int(os.environ.get('DJANGO_CONN_MAX_AGE', '300')),
        'CONN_HEALTH_CHECKS': True,
    }


try:
    import pymysql
    # Django 6's mysql backend gates on mysqlclient >= (2, 2, 1). pymysql's own
    # version_info is lower, so advertise a compatible one before the shim.
    pymysql.version_info = (2, 2, 8, 'final', 0)
    pymysql.install_as_MySQLdb()
except Exception:
    pass

_ORDERS_DB = _load_orders_db()
if _ORDERS_DB:
    DATABASES['orders'] = _ORDERS_DB
    DATABASE_ROUTERS = ['online_b2b.db_router.OrdersRouter']

# ── Persist Django's OWN tables (auth / sessions / admin) on a real DB ──────
# The default connection is SQLite (fine for LAN/dev). But a host with NO
# persistent disk (e.g. Render free) wipes that file on every deploy/restart →
# users + logins vanish. Set DJANGO_DEFAULT_DB=mysql on such a host to put the
# 'default' connection on the SAME MySQL/TiDB as the business data, so auth +
# sessions persist. The OrdersRouter still keeps the engine-owned business tables
# migration-free; only Django's own tables get created there. Unset (LAN/dev) →
# 'default' stays SQLite, unchanged.
if _ORDERS_DB and os.environ.get('DJANGO_DEFAULT_DB', '').lower() in (
        'mysql', 'tidb', 'orders'):
    DATABASES['default'] = dict(_ORDERS_DB)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files storage.
#  • Production (DEBUG off): CONTENT-HASHED filenames + manifest + compression, so
#    every deploy serves a NEW url and browsers can never keep serving a stale
#    JS/CSS from cache (the root cause of "old code after a change" bugs). The
#    resilient subclass falls back to the plain name if an entry is missing rather
#    than 500-ing the page.
#  • Dev (DEBUG on): plain compressed storage — runserver serves straight from the
#    source dirs, so no `collectstatic`/manifest is needed while developing.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage" if DEBUG
            else "renee_cosmetics.storage.ResilientManifestStaticFilesStorage"
        ),
    },
}

# Media — uploaded PO files + generated workbooks (Phase 0). Disk cache only;
# the system of record for orders is MySQL `renee_orders` (the engine's store).
# MEDIA_ROOT is env-configurable so a HOST can point it at durable storage: on
# Render the local disk is EPHEMERAL (wiped on every deploy/restart), so an
# in-flight upload/review + generated workbooks would be lost. Set MEDIA_ROOT to a
# mounted persistent disk (e.g. /data/media — needs a paid Render plan) to keep
# them. Defaults to the repo's ./media for local/LAN hosting (durable there).
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT') or (BASE_DIR / 'media'))
try:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)     # ensure the root exists at boot
except OSError:
    pass

# A large PO's review form carries 4 decision fields per FLAGGED line
# (aff_key / aff_action / aff_override_cp / aff_remark). A few hundred affected
# lines exceeds Django's default 1000-field cap (a DoS guard) → TooManyFieldsSent
# on Lock / Discard / Generate. This is a trusted internal LAN tool processing
# genuinely large POs, so raise the cap generously. File-upload size guards are
# unaffected (DATA_UPLOAD_MAX_MEMORY_SIZE stays default).
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

# The Triangular Validation page lets the operator drop a WHOLE folder (e.g. the
# entire day's Package-Data folder, sub-folders and all) — easily > Django's
# default 100-file cap → TooManyFilesSent. Trusted internal LAN tool; raise it
# generously (still bounded as a DoS backstop). Upload size guards unaffected.
DATA_UPLOAD_MAX_NUMBER_FILES = 5000

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'departments'
# Central logout target (standard: keep auth redirects declared here, not hardcoded
# in the view). CustomLogoutView still works; this makes the config the source of truth.
LOGOUT_REDIRECT_URL = 'home'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
