from django.urls import path

from . import views
from . import full_validation_views as _fullval  # STANDALONE feature (removable)

urlpatterns = [
    path('', views.CentralHubView.as_view(), name='b2b_dashboard'),
    # ── Full Validation (standalone; delete these 3 lines + the module/template/
    #    sidebar link to remove the whole feature) ────────────────────────────
    path('full-validation/', _fullval.full_validation, name='b2b_full_validation'),
    path('full-validation/run/', _fullval.full_validation_run, name='b2b_full_validation_run'),
    path('full-validation/<str:token>/download/', _fullval.full_validation_download,
         name='b2b_full_validation_download'),
    path('online/', views.dashboard, name='b2b_online'),
    path('offline/', views.OfflineBranchView.as_view(), name='b2b_offline'),
    path('analytics/', views.AnalyticsView.as_view(), name='b2b_analytics'),
    path('analytics/sku/', views.SkuDemandView.as_view(), name='b2b_sku_demand'),
    path('analytics/sku/export/', views.sku_demand_export, name='b2b_sku_demand_export'),
    path('rules/', views.RulesView.as_view(), name='b2b_rules'),
    path('exceptions/', views.exceptions_page, name='b2b_exceptions'),
    path('exceptions/add/', views.exception_add, name='b2b_exception_add'),
    path('exceptions/<int:row_id>/update/', views.exception_update, name='b2b_exception_update'),
    path('exceptions/<int:row_id>/delete/', views.exception_delete, name='b2b_exception_delete'),
    path('rules/template/<str:slug>/', views.MarketplaceTemplateView.as_view(),
         name='b2b_template'),
    path('orders/', views.orders, name='b2b_orders'),
    path('orders/more/', views.orders_more, name='b2b_orders_more'),
    path('lines/', views.lines, name='b2b_lines'),
    path('lines/more/', views.lines_more, name='b2b_lines_more'),
    path('daily/', views.daily_tasks, name='b2b_daily'),
    path('daily/toggle/', views.daily_tasks_toggle, name='b2b_daily_toggle'),
    path('daily/hold-reason/', views.daily_hold_reason, name='b2b_daily_hold_reason'),
    path('daily/email/preview/', views.daily_email_preview, name='b2b_daily_email_preview'),
    path('daily/email/send/', views.daily_email_send, name='b2b_daily_email_send'),
    path('daily/adhoc/add/', views.daily_adhoc_add, name='b2b_daily_adhoc_add'),
    path('daily/adhoc/toggle/', views.daily_adhoc_toggle, name='b2b_daily_adhoc_toggle'),
    path('daily/adhoc/delete/', views.daily_adhoc_delete, name='b2b_daily_adhoc_delete'),
    path('ui-lab/', views.ui_lab, name='b2b_ui_lab'),
    path('ui-lab/search/', views.ui_lab_search, name='b2b_ui_lab_search'),
    path('issues/', views.issues, name='b2b_issues'),
    path('issues/export/', views.issues_export, name='b2b_issues_export'),
    path('issues/email/preview/', views.issues_email_preview, name='b2b_issues_email_preview'),
    path('issues/email/send/', views.issues_email_send, name='b2b_issues_email_send'),
    path('issues/save/', views.issues_save, name='b2b_issues_save'),
    path('issues/save-bulk/', views.issues_save_bulk, name='b2b_issues_save_bulk'),
    path('issues/fix-ean/', views.issues_fix_ean, name='b2b_issues_fix_ean'),
    path('tat/', views.tat, name='b2b_tat'),
    path('tat/save/', views.tat_save, name='b2b_tat_save'),
    path('tat/export/', views.tat_export, name='b2b_tat_export'),
    path('sku-summary/', views.sku_summary, name='b2b_sku_summary'),
    path('sku-summary/lines/', views.sku_summary_lines, name='b2b_sku_summary_lines'),
    path('export/', views.export, name='b2b_export'),
    path('upload/', views.upload, name='b2b_upload'),
    path('bulk/', views.bulk_upload, name='b2b_bulk_upload'),
    path('bulk/<str:token>/', views.bulk_review, name='b2b_bulk_review'),
    path('bulk/<str:token>/confirm/', views.bulk_confirm, name='b2b_bulk_confirm'),
    path('review/<str:token>/', views.review, name='b2b_review'),
    path('review/<str:token>/confirm/', views.confirm, name='b2b_confirm'),
    path('review/<str:token>/fix-ean/', views.fix_ean, name='b2b_fix_ean'),
    path('review/<str:token>/save-decision/', views.save_decision, name='b2b_save_decision'),
    path('review/<str:token>/d365/', views.generate_d365, name='b2b_generate_d365'),
    path('review/<str:token>/save-later/', views.SaveReviewLaterView.as_view(), name='b2b_save_review_later'),
    path('review/<str:token>/email-issue/', views.draft_email_send, name='b2b_review_email_issue'),
    path('review/<str:token>/discard/', views.discard, name='b2b_discard'),
    path('review/<str:token>/download/', views.review_download, name='b2b_review_download'),
    path('review/<str:token>/download/completed/', views.review_download_completed,
         name='b2b_review_download_completed'),
    path('drafts/', views.DraftsView.as_view(), name='b2b_drafts'),
    path('gt-select/', views.GtSelectView.as_view(), name='b2b_gt_select'),
    path('gt-select/upload/', views.gt_select_upload, name='b2b_gt_select_upload'),
    path('gt-select/<str:token>/', views.gt_select_preview, name='b2b_gt_select_preview'),
    path('gt-select/<str:token>/confirm/', views.gt_select_confirm, name='b2b_gt_select_confirm'),
    path('gt-select/<str:token>/discard/', views.gt_select_discard, name='b2b_gt_select_discard'),
    path('item-master/', views.ItemMasterView.as_view(), name='b2b_item_master'),
    path('item-master/search/', views.item_master_search, name='b2b_item_master_search'),
    path('item-master/export/', views.item_master_export, name='b2b_item_master_export'),
    path('item-master/add/', views.item_master_add, name='b2b_item_master_add'),
    path('item-master/upload/', views.item_master_upload, name='b2b_item_master_upload'),
    path('item-master/<str:token>/', views.item_master_preview, name='b2b_item_master_preview'),
    path('item-master/<str:token>/confirm/', views.item_master_confirm, name='b2b_item_master_confirm'),
    path('item-master/<str:token>/discard/', views.item_master_discard, name='b2b_item_master_discard'),
    path('ship-to/', views.ShipToView.as_view(), name='b2b_ship_to'),
    path('ship-to/search/', views.ship_to_search, name='b2b_ship_to_search'),
    path('ship-to/add/', views.ship_to_add, name='b2b_ship_to_add'),
    path('ship-to/seed/', views.ship_to_seed, name='b2b_ship_to_seed'),
    path('ship-to/upload/', views.ship_to_upload, name='b2b_ship_to_upload'),
    path('ship-to/<int:row_id>/edit/', views.ship_to_edit, name='b2b_ship_to_edit'),
    path('ship-to/<int:row_id>/delete/', views.ship_to_delete, name='b2b_ship_to_delete'),
    path('ship-to/<str:token>/', views.ship_to_preview, name='b2b_ship_to_preview'),
    path('ship-to/<str:token>/confirm/', views.ship_to_confirm, name='b2b_ship_to_confirm'),
    path('ship-to/<str:token>/discard/', views.ship_to_discard, name='b2b_ship_to_discard'),
    path('sales-validation/', views.SalesValidationView.as_view(),
         name='b2b_sales_validation'),
    path('sales-validation/run/', views.sales_validation_run,
         name='b2b_sales_validation_run'),
    path('sales-validation/<str:token>/download/',
         views.sales_validation_download, name='b2b_sales_validation_download'),
    path('run/<int:run_id>/', views.run_detail, name='b2b_run_detail'),
    path('run/<int:run_id>/download/', views.download, name='b2b_download'),
    path('run/<int:run_id>/d365/', views.download_d365, name='b2b_download_d365'),
    path('run/<int:run_id>/delete/', views.run_delete, name='b2b_run_delete'),
]
