from django.urls import path
from django.views.generic import RedirectView

from . import views
from . import full_validation_views as _fullval  # STANDALONE feature (removable)
from . import views_record_verification as _rv  # STANDALONE feature (removable)
from . import inventory_views as _inv  # STANDALONE feature (removable)

urlpatterns = [
    # Hub removed (limited build) — landing redirects to the Tracker. The name
    # 'b2b_dashboard' is KEPT so every breadcrumb/brand {% url %} still resolves.
    path('', RedirectView.as_view(pattern_name='b2b_tracker', permanent=False), name='b2b_dashboard'),
    # ── Full Validation (standalone; delete these 3 lines + the module/template/
    #    sidebar link to remove the whole feature) ────────────────────────────
    path('full-validation/', _fullval.full_validation, name='b2b_full_validation'),
    path('full-validation/run/', _fullval.full_validation_run, name='b2b_full_validation_run'),
    path('full-validation/<str:token>/download/', _fullval.full_validation_download,
         name='b2b_full_validation_download'),
    # ── Record Verification (standalone; delete these lines + the module/
    #    template/service/nav link to remove the whole feature) ─────────────────
    path('record-verify/', _rv.RecordVerificationView.as_view(), name='b2b_record_verify'),
    path('record-verify/log/', _rv.RecordVerificationLogView.as_view(), name='b2b_record_verify_log'),
    path('record-verify/log/clear/', _rv.RecordVerificationClearLogView.as_view(), name='b2b_record_verify_clear_log'),
    path('record-verify/run/', _rv.RecordVerificationRunView.as_view(), name='b2b_record_verify_run'),
    path('record-verify/<str:token>/confirm/', _rv.RecordVerificationConfirmView.as_view(), name='b2b_record_verify_confirm'),
    path('record-verify/<str:token>/capture/', _rv.RecordVerificationCaptureView.as_view(), name='b2b_record_verify_capture'),
    path('record-verify/<str:token>/save-later/', _rv.RecordVerificationSaveLaterView.as_view(), name='b2b_record_verify_save_later'),
    path('record-verify/<str:token>/discard/', _rv.RecordVerificationDiscardView.as_view(), name='b2b_record_verify_discard'),
    path('record-verify/<str:token>/discard-part/', _rv.RecordVerificationDiscardPartView.as_view(), name='b2b_record_verify_discard_part'),
    path('record-verify/<str:token>/download/', _rv.RecordVerificationDownloadView.as_view(),
         name='b2b_record_verify_download'),
    # ── Inventory — Fill-Rate cockpit (standalone; delete these lines + the
    #    module/service/templates/sidebar link to remove the whole feature) ────
    # Channel SKU Map — per-channel vendor SKU-code → EAN → item (Swiggy/HG/…)
    path('channel-map/', views.channel_map_redirect, name='b2b_channel_map'),
    path('channel-map/upload/', views.channel_map_upload, name='b2b_channel_map_upload'),
    path('channel-map/add/', views.channel_map_add, name='b2b_channel_map_add'),
    path('channel-map/<int:row_id>/delete/', views.channel_map_delete,
         name='b2b_channel_map_delete'),
    path('inventory/', _inv.inventory, name='b2b_inventory'),
    path('inventory/export/', _inv.inventory_export, name='b2b_inventory_export'),
    path('inventory/bin-coverage/', _inv.inventory_bin_coverage, name='b2b_inventory_bin_coverage'),
    path('inventory/upload/', _inv.inventory_upload, name='b2b_inventory_upload'),
    path('inventory/bins/', _inv.inventory_bins, name='b2b_inventory_bins'),
    path('inventory/rule/add/', _inv.inventory_rule_add, name='b2b_inventory_rule_add'),
    path('inventory/rule/<int:rule_id>/delete/', _inv.inventory_rule_delete,
         name='b2b_inventory_rule_delete'),
    path('inventory/bin/set/', _inv.inventory_bin_set, name='b2b_inventory_bin_set'),
    path('inventory/apply/', _inv.inventory_apply, name='b2b_inventory_apply'),
    path('inventory/<str:token>/', _inv.inventory_preview, name='b2b_inventory_preview'),
    path('inventory/<str:token>/confirm/', _inv.inventory_confirm,
         name='b2b_inventory_confirm'),
    path('inventory/<str:token>/discard/', _inv.inventory_discard,
         name='b2b_inventory_discard'),
    path('online/', views.dashboard, name='b2b_online'),
    path('offline/', views.OfflineBranchView.as_view(), name='b2b_offline'),
    path('rules/', views.RulesView.as_view(), name='b2b_rules'),
    path('exceptions/', views.exceptions_page, name='b2b_exceptions'),
    path('exceptions/add/', views.exception_add, name='b2b_exception_add'),
    path('exceptions/<int:row_id>/update/', views.exception_update, name='b2b_exception_update'),
    path('exceptions/<int:row_id>/delete/', views.exception_delete, name='b2b_exception_delete'),
    path('rules/template/<str:slug>/', views.MarketplaceTemplateView.as_view(),
         name='b2b_template'),
    # READ-ONLY partial for the Process-PO upload page's live marketplace panel.
    path('mp-profile/<str:mp>/', views.b2b_mp_profile, name='b2b_mp_profile'),
    path('orders/', views.orders, name='b2b_orders'),  # compat redirect → tracker
    path('order/<path:po>/', views.OrderDetailView.as_view(), name='b2b_order_detail'),
    path('tracker/', views.TrackerView.as_view(), name='b2b_tracker'),
    path('tracker/export/', views.TrackerExportView.as_view(), name='b2b_tracker_export'),
    path('tracker/billing/', views.TrackerBillingView.as_view(), name='b2b_tracker_billing'),
    path('tracker/today/', views.TrackerTodayView.as_view(), name='b2b_tracker_today'),
    path('tracker/insights/', views.TrackerInsightsView.as_view(), name='b2b_tracker_insights'),
    path('tracker/add/', views.TrackerAddView.as_view(), name='b2b_tracker_add'),
    path('tracker/<int:row_id>/delete/', views.TrackerDeleteView.as_view(), name='b2b_tracker_delete'),
    path('lines/', views.lines, name='b2b_lines'),
    path('lines/more/', views.lines_more, name='b2b_lines_more'),
    path('daily/', views.daily_tasks, name='b2b_daily'),
    path('daily/toggle/', views.daily_tasks_toggle, name='b2b_daily_toggle'),
    path('daily/hold-reason/', views.daily_hold_reason, name='b2b_daily_hold_reason'),
    path('daily/email/preview/', views.daily_email_preview, name='b2b_daily_email_preview'),
    path('daily/email/send/', views.daily_email_send, name='b2b_daily_email_send'),
    path('daily/adhoc/add/', views.daily_adhoc_add, name='b2b_daily_adhoc_add'),
    path('daily/adhoc/toggle/', views.daily_adhoc_toggle, name='b2b_daily_adhoc_toggle'),
    path('daily/adhoc/delete/', views.daily_adhoc_delete, name='b2b_daily_adhoc_delete'),
    path('issues/', views.issues, name='b2b_issues'),
    path('issues/export/', views.issues_export, name='b2b_issues_export'),
    path('issues/email/preview/', views.issues_email_preview, name='b2b_issues_email_preview'),
    path('issues/email/send/', views.issues_email_send, name='b2b_issues_email_send'),
    path('issues/email/retry/', views.issues_email_retry, name='b2b_issues_email_retry'),
    path('issues/save/', views.issues_save, name='b2b_issues_save'),
    path('issues/save-bulk/', views.issues_save_bulk, name='b2b_issues_save_bulk'),
    path('issues/fix-ean/', views.issues_fix_ean, name='b2b_issues_fix_ean'),
    path('export/', views.export, name='b2b_export'),
    path('upload/', views.upload, name='b2b_upload'),
    path('bulk/', views.bulk_upload, name='b2b_bulk_upload'),
    path('bulk/<str:token>/', views.bulk_review, name='b2b_bulk_review'),
    path('bulk/<str:token>/confirm/', views.bulk_confirm, name='b2b_bulk_confirm'),
    path('review/<str:token>/', views.review, name='b2b_review'),
    path('review/<str:token>/confirm/', views.confirm, name='b2b_confirm'),
    path('review/<str:token>/fix-ean/', views.fix_ean, name='b2b_fix_ean'),
    path('review/<str:token>/save-decision/', views.save_decision, name='b2b_save_decision'),
    path('review/<str:token>/d365/', views.generate_d365, name='b2b_generate_d365'),
    path('review/<str:token>/save-later/', views.SaveReviewLaterView.as_view(), name='b2b_save_review_later'),
    path('review/<str:token>/email-issue/', views.draft_email_send, name='b2b_review_email_issue'),
    path('review/<str:token>/discard/', views.discard, name='b2b_discard'),
    path('review/<str:token>/download/', views.review_download, name='b2b_review_download'),
    path('review/<str:token>/download/completed/', views.review_download_completed,
         name='b2b_review_download_completed'),
    path('drafts/', views.DraftsView.as_view(), name='b2b_drafts'),
    path('gt-select/', views.GtSelectView.as_view(), name='b2b_gt_select'),
    path('gt-select/upload/', views.GtSelectPreviewView.as_view(), name='b2b_gt_select_upload'),
    path('gt-select/<str:token>/', views.gt_select_preview, name='b2b_gt_select_preview'),
    path('gt-select/<str:token>/confirm/', views.GtSelectImportView.as_view(), name='b2b_gt_select_confirm'),
    path('gt-select/<str:token>/discard/', views.gt_select_discard, name='b2b_gt_select_discard'),
    path('item-master/', views.ItemMasterView.as_view(), name='b2b_item_master'),
    path('item-master/search/', views.item_master_search, name='b2b_item_master_search'),
    path('item-master/export/', views.item_master_export, name='b2b_item_master_export'),
    path('item-master/add/', views.item_master_add, name='b2b_item_master_add'),
    path('item-master/upload/', views.item_master_upload, name='b2b_item_master_upload'),
    path('item-master/<str:token>/', views.item_master_preview, name='b2b_item_master_preview'),
    path('item-master/<str:token>/confirm/', views.item_master_confirm, name='b2b_item_master_confirm'),
    path('item-master/<str:token>/discard/', views.item_master_discard, name='b2b_item_master_discard'),
    path('ship-to/', views.ShipToView.as_view(), name='b2b_ship_to'),
    path('ship-to/search/', views.ship_to_search, name='b2b_ship_to_search'),
    path('ship-to/export/', views.ship_to_export, name='b2b_ship_to_export'),
    path('ship-to/add/', views.ship_to_add, name='b2b_ship_to_add'),
    path('ship-to/field/add/', views.ship_to_field_add, name='b2b_ship_to_field_add'),
    path('ship-to/field/delete/', views.ship_to_field_delete, name='b2b_ship_to_field_delete'),
    path('ship-to/seed/', views.ship_to_seed, name='b2b_ship_to_seed'),
    path('ship-to/upload/', views.ship_to_upload, name='b2b_ship_to_upload'),
    path('ship-to/<int:row_id>/edit/', views.ship_to_edit, name='b2b_ship_to_edit'),
    path('ship-to/<int:row_id>/delete/', views.ship_to_delete, name='b2b_ship_to_delete'),
    path('eka-data/', views.EkaDataView.as_view(), name='b2b_eka_data'),
    path('eka-data/add/', views.eka_data_add, name='b2b_eka_data_add'),
    path('eka-data/upload/', views.eka_data_upload, name='b2b_eka_data_upload'),
    path('eka-data/<int:row_id>/update/', views.eka_data_update, name='b2b_eka_data_update'),
    path('ship-to/<str:token>/', views.ship_to_preview, name='b2b_ship_to_preview'),
    path('ship-to/<str:token>/confirm/', views.ship_to_confirm, name='b2b_ship_to_confirm'),
    path('ship-to/<str:token>/discard/', views.ship_to_discard, name='b2b_ship_to_discard'),
    path('run/<int:run_id>/', views.run_detail, name='b2b_run_detail'),
    path('run/<int:run_id>/export/', views.run_export, name='b2b_run_export'),
    path('run/<int:run_id>/download/', views.download, name='b2b_download'),
    path('run/<int:run_id>/download/completed/', views.download_completed, name='b2b_download_completed'),
    path('run/<int:run_id>/d365/', views.download_d365, name='b2b_download_d365'),
    path('run/<int:run_id>/delete/', views.run_delete, name='b2b_run_delete'),
    # Setup — switch the active DB target (local ↔ TiDB server). Staff only.
    path('setup/', views.SetupView.as_view(), name='b2b_setup'),
]
